
ubiquity_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

ubiquity_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel  : 'left_wheel_joint'
  right_wheel : 'right_wheel_joint'
  publish_rate: 50.0
  pose_covariance_diagonal: [0.2, 0.2, 0.2, 0.2, 0.2, 0.2]
  twist_covariance_diagonal: [0.2, 0.2, 0.2, 0.2, 0.2, 0.2]

  cmd_vel_timeout: 0.25
  enable_odom_tf: true
  base_frame_id: base_footprint

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : false
      max_velocity           : 1.0   # m/s
      has_acceleration_limits: true
      max_acceleration       : 1.1   # m/s^2
  angular:
    z:
      has_velocity_limits    : false
      max_velocity           : 2.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 5.0   # rad/s^2
